version: 2.1

jobs:
  build-and-publish:
    docker:
      - image: cimg/node:20.10
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: yarn

      - run:
          name: Test
          command: yarn test

      - run:
          name: Build
          command: yarn build

      - run:
          name: Configure .npmrc
          command: |
            sed -i 's/GH_TOKEN/GH_PACKAGE_WRITE/g' .npmrc

      - run:
          name: Publish
          command: npm publish

workflows:
  build_and_deploy:
    jobs:
      - build-and-publish:
          filters:
            branches:
              only: main
          context:
            - GithubPackages
