on: pull_request_review

name: Label approved pull requests

jobs:
  labelWhenApproved:
    name: Label when approved
    runs-on: ubuntu-latest
    steps:
      - name: Label when approved
        uses: hmarr/label-when-approved-action@v1
        env:
          APPROVALS: '1'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: '🚀 Approved 🚀'
          REMOVE_LABEL: 'Ready%20for%20review%20👀'
