
on: pull_request_review

name: Label approved pull requests

jobs:
  - uses: actions/checkout@v2
    with:
      fetch-depth: 0 # Required to retrieve git history

  - uses: chromaui/action@v1
    with:
      token: ${{ secrets.GITHUB_TOKEN }}
      projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}


name: "Chromatic"
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        yarn && yarn build-storybook
    - uses: chromaui/action@v1
      with: 
        projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        token: ${{ secrets.GITHUB_TOKEN }}